config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  root  'homes#home'
  namespace :admin do
    resources :users
    get 'home/', to: 'homes#home'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
# frozen_string_literal: true

class Chatroom < ApplicationRecord
  has_many                :messages, dependent: :destroy
  has_and_belongs_to_many :users
end

app/models/direct_chatroom.rb
# frozen_string_literal: true

class DirectChatroom < Chatroom
end

app/models/group_chatroom.rb
# frozen_string_literal: true

class GroupChatroom < Chatroom
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  has_many_attached :files

  validates_presence_of :body, :title
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_and_belongs_to_many :chatrooms
  has_many                :messages
end

app/controllers/admin/homes_controller.rb
# frozen_string_literal: true

module Admin
  class HomesController < AdminController
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    before_action :find_user, only: %i[show edit update destroy]
    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_user_path(@user)
      else
        render :new
      end
    end

    def update
      if @user.update(user_params)
        redirect_to admin_user_path(@user)
      else
        render :edit
      end
    end

    def destroy
      redirect_to admin_users_path, notice: 'User was deleted' if @user.delete
    end

    private

    def user_params
      params.require(:user).permit(:email, :first_name, :second_name, :password)
    end

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ActionController::Base
  layout 'admin/application'

  before_action :authenticate_user!
  before_action :check_admin_access

  private

  def check_admin_access
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def home
    redirect_to admin_home_path if current_user&.admin?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/homes/home.html.haml
%br/
.row
  .col-2
  .col-8
    %h1 Welcome Admin
  .col-2

app/views/admin/users/_form.html.haml
- url = @user.new_record? ? admin_users_path : admin_user_path
= simple_form_for(@user, url: url, input_html: { class: 'modal-form' }) do |f|
  .form-group
    .col-md-12
      = f.input :email, placeholder: 'user@domain.com', input_html: { class: "form-control" }, label: 'Email'
      %br
      = f.input :first_name, input_html: { class: 'form-control'}, label: 'First name'
      %br
      = f.input :second_name, input_html: { class: 'form-control'}, label: 'Second name'
      %br
      = f.input :password, input_html: { class: 'form-control'}, label: 'Password'
  .form-actions
    .col-md-12
      %br
      = f.button :submit, @user.new_record? ? 'Create' : 'Update', class: "btn btn-success pull-right"
      = link_to 'Back', admin_users_path, class: 'btn btn-danger'

app/views/admin/users/edit.html.haml
.row
  .col-md-12
    %h3= 'Edit user'
  .col-md-10.col-md-offset-1
    = render 'form'

app/views/admin/users/index.html.haml
%h1 All Users
%br/

= link_to 'New user', new_admin_user_path, class: 'btn btn-success'

%p/

%table.table
  %thead
    %tr
      %th Email
      %th First name
      %th Second name
      %th
      %th
      %th
  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.first_name
      %td= user.second_name
      %td= link_to 'Show', admin_user_path(user), class: 'btn btn-success'
      %td= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-info'
      %td= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/admin/users/new.html.haml
.row
  .col-md-12
    %h3= 'New user'
  .col-md-10.col-md-offset-1
    = render 'form'

app/views/admin/users/show.html.haml
.row
  .col-md-12
    %h3= 'Edit user'
  .col-md-10.col-md-offset-1
    %table.table
      %tr
        %td Email
        %td= @user.email
      %tr
        %td First name
        %td= @user.first_name
      %tr
        %td Second name
        %td= @user.second_name

app/views/homes/home.html.haml
%br/
.row
  .col
  .col
    %h1 Welcome
  .col

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand.navbar-dark.bg-dark
  .container
    .navbar-brand Chat
    .navbar-collapse
      %ul.navbar-nav
        %li
          = link_to 'Home', root_path, class: "nav-link"

    %ul.navbar-nav.login
      - if user_signed_in?
        %li
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        %li
          = link_to 'SignIn', new_user_session_path, class: "nav-link"

app/views/layouts/admin/_navbar.html.haml
%nav.navbar.navbar-expand.navbar-dark.bg-primary
  .container
    .navbar-brand Admin Panel | Chat
    .navbar-collapse
      %ul.navbar-nav
        %li
          = link_to 'Home', root_path, class: "nav-link"
        %li
          = link_to 'Users', admin_users_path, class: "nav-link"

    %ul.navbar-nav.login
      - if user_signed_in?
        %li
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        %li
          = link_to 'SignIn', new_user_session_path, class: "nav-link"

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsChatApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
  %body
    = render 'layouts/admin/navbar'
    %div{:class => "container #{controller_name} #{action_name}"}
      - if flash.any?
        - flash.keys.each do |key|
          %div{:class => ("alert alert-#{key.to_s} alert-dismissible"), role: "alert"}
            %button.close{ 'aria-label' => "Close", 'data-dismiss' => "alert", type: "button"}
              %span{'aria-hidden' => "true"}  ×
            = flash[key]
    %br/
    .row
      .col-3
      .col-6
        = yield
      .col-3

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsChatApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
  %body
    = render 'layouts/navbar'
    %div{:class => "container #{controller_name} #{action_name}"}
      - if flash.any?
        - flash.keys.each do |key|
          %div{:class => ("alert alert-#{key.to_s} alert-dismissible"), role: "alert"}
            %button.close{ 'aria-label' => "Close", 'data-dismiss' => "alert", type: "button"}
              %span{'aria-hidden' => "true"}  ×
            = flash[key]
    %br/
    .row
      .col-3
      .col-6
        = yield
      .col-3